### ISSUE TITLE
Add labels to rule references

### ISSUE THREAD

**Issue by lukaseder** [Chrriis/RRDiagram#22]
I'm considering adding support for labels to rule references (see https://github.com/jOOQ/jOOQ/issues/10251). For example, I'd like to be able to define this grammar:

```
function = 'DATEDIFF' '(' (! field "fromDate" !) ',' (! field "toDate" !) ')';
field = ...;
```

The output should be this:

![image](https://user-images.githubusercontent.com/734593/83864535-284d3b00-a725-11ea-93d9-6c43041d8a43.png)

But the link anchors should point to `field`.

Any thoughts? Preferences on syntax? My suggestion uses a `(! ... !)` syntax similar to comments `(* ... *)` and expects the name of the expression and an optional label. `(! expression !)` is the same as `expression`

An alternative way to implement this would be to have label definitions in addition to rule definitions, such as:

```
function = 'DATEDIFF' '(' fromDate ',' toDate ')';
"fromDate" = field;
"toDate" = field;
field = ...;
```

Syntax again debatable. These labels would not appear in the output, just like before, but they would now be global. I personally prefer local labels.

**Comment by Chrriis** [comment]
It is possible to replace special sequence with custom elements.

For example, with a BNF definition like:
`Rule1 = a (? custom field label ?) b`

... and a special sequence element provider like this one:
```
grammarToRRDiagram.setSpecialSequenceElementProvider(new SpecialSequenceElementProvider() {
  @Override
  public RRElement getElement(String text) {
    if(text.startsWith("custom")) {
      String[] tokens = text.split(" ");
      return new RRText(Type.RULE, tokens[2], grammarToRRDiagram.getRuleLinkProvider().getLink(tokens[1]));
    }
    return null;
  }
});
```

It is possible to get:
![image](https://github.com/Chrriis/RRDiagram/assets/1174202/c11c9c49-d2e3-460c-b7d0-0a90e8485a2d)
... with the link on label being "#field".

Of course, because any element can be returned, I suppose any RRElement subclass can be created with whatever representation.

**Comment by lukaseder** [comment]
Great to hear from you, @Chrriis. Hope you're doing great! And thanks a lot for your work on this! I'll look into this soon, on the jOOQ side: https://github.com/jOOQ/jOOQ/issues/16099
